### PR TITLE
Requested fixes for winter

### PR DESCRIPTION
**Pull request by Blakeley00**
All "not authorised" missing news items fixed using text copies from page 7 & 8. They also had missing side menu, header info & next/prev nav links compared to other working news pages so that was fixed too.

Oversized pages fixed too. "pre" tag sections were overriding the div sizes so I found the offending lines and separated them to new lines.

Slight wording adjustment on downloads page section titles to match improved wording used on sourcforge pages now.

### CODE REVIEW

**Comment by wintertime** [comment]
Thank you for all this, it's even more than you promised.
I merged it to sourceforge repo and added a few more tweaks myself.

**Comment by Blakeley00** [comment]
Hi Winter. Something has gone wrong as I noticed my fixes to roadmap and downloads haven't gone through?

**Comment by wintertime** [comment]
It is only a matter of time. If you look at the history [on sf](https://sourceforge.net/p/freecol/git/ci/master/tree/) you'll see your changes are there in between mine.
I'm with you in waiting, but Mike is very low on spare time and of the (semi-)active project members only he can do the webserver upload. He will upload our changes when he is able to.

**Comment by Blakeley00** [comment]
> It is only a matter of time. If you look at the history [on sf](https://sourceforge.net/p/freecol/git/ci/master/tree/) you'll see your changes are there in between mine.
> I'm with you in waiting, but Mike is very low on spare time and of the (semi-)active project members only he can do the webserver upload. He will upload our changes when he is able to.

Ahh okay.. yup I see them on SF.. just got confused as the changes aren't on the github copy despite originating from here haha. Guess I still don't really understand how it works between the 2 sites. 

FYI Mike has just done an upload the website still doesn't have the fixed roadmap page and some other stuff though. You sure something isn't wrong?

**Comment by wintertime** [comment]
Yeah, this is getting confusing with the 2 sites. I just posted on sf forum.
Basically, Sourceforge is still the main page. GitHub is the mirror with a currently broken autoupdate and irregular manual updates for getting a nightly out. It's still undecided when that is switched around.

**Pull request closed without merging**
