### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Blakeley00**
Removed version numbers from current status and main index home page to reduce places that 'age' the site and make the project look abandoned and also reduce website update work when new versions are released.

Have done major update to downloads section that features the nightly releases and removed some duplication issues.

No doubt you guys will want to further alter and improve my suggestions. But hopefully I've helped get the ball rolling.

### CODE REVIEW

**Comment by wintertime** [comment]
Nice that you found out how to do this (got your email and btw. the sourceforge repository seems to still be the main one so its not important to have it as a pull request, a link would also work).
It is always good when people want to help.
Sadly, I was about to do a conflicting change to the homepage this weekend. I would have kept the 0.11.6 Link and added another Link to the nightly release above.
Additionally, I'm not so sure if it's really helpful to remove information on current version on the other page?

**Comment by Blakeley00** [comment]
Hi winter, 

> Nice that you found out how to do this (got your email and btw. the sourceforge repository seems to still be the main one so its not important to have it as a pull request, a link would also work).
> It is always good when people want to help.
No worries mate. So instead of a pull request I just post links to my commits? if so where would you want that posted?

> Sadly, I was about to do a conflicting change to the homepage this weekend. I would have kept the 0.11.6 Link and added another Link to the nightly release above.
Yours sounds even better as yeah I wanted to put a nightly releases link on the main page but thought I'd start simple with my changes haha. My link is still the same as the old one, I just removed the version number so that you don't have to change it every single time you do a new release. Plus every who visits the site sees it and thinks it hasn't been touched in years. Having that version number 'ages things' somewhat to regular lurkers.

> Additionally, I'm not so sure if it's really helpful to remove information on current version on the other page?
Removing the version number from the status page means you don't have to update that page every time a new version is released. The line blow it about the project being in constant developement that links to the sourceforge page seems good enough on its own. However its up to you mate, I'm trying to reduce mentining of version numbers so you don't have to update 20 different places on the site when a new one is released haha.

Check out my new downloads page submission (hopefully it worked as weird things happened when I tried to push through a new downloads.html page changes pull request (possibly becuase I've already done a previous pull request under the master branch?). I can see it above so I think it worked and just added it to the existing pull request. You'll probably want to do more with it or do something different but hopefully I've given you some ideas for improving it and getting people to the nightly releases. I've emailed you some pictures of the differences. The nightly releases needs a new icon though.

Here's the old version which has duplicated headings and duplicate java downloads:
image

And here's my modified one with all the new stuff detailed in the commit.. I also H4'ed the test and stable download section headings and stuck in another colony picture to better separate the new nightly section from the stable release section:
image

**Comment by wintertime** [comment]
Well, I did not try to discourage you from using the pull request feature, just mentioned an alternative in case of you having problems with it. One problem you encountered is, when you make later changes to the branch you submitted the pull request for, the pull request is changed. That means, for unrelated changes people on github usually create a different branch named after the changes and submit another pull request.
Btw., this should make no difference with this, though this github mirror is not always up to date, the main repo is still on sourceforge: https://sourceforge.net/p/freecol/git/ci/master/tree/
It is still undecided if/when a real switch to github is done (cause of time constraints mentioned below). This also affects your changes to the download page, because the next full release might be still uploaded to sourceforge firstly, while nightly releases happen on github, but you deleted the sourceforge links already.
I'm also kinda hoping for more feedback from other people on the website stuff, but everyone seems to still have real life time constraints since a longer time ago, including the project lead Mike Pope.

**Comment by Blakeley00** [comment]
thanks for the info. Makes sense now.

Nah I haven't deleted ANY sourceforge links. All I did was remove 1 duplicate download link and 1 duplicate title text and then inserted all the new github nightly release stuff above the old links. If you look closely you'll see all the old download links are still there completely unchanged.

**Comment by wintertime** [comment]
Thank you for helping with this.
I did some rebasing onto the sourceforge master and used most of your changes, except the one in status html. (Btw., it is safer to create a new branch than use your fork's master for pull requests.)
I then added a number of small website updates myself, too. Please, get last version from https://sourceforge.net/p/freecol/git if you'd like to see them, as it may take a bit of time until David triggers an update to the GitHub mirror!

**Pull request closed without merging**
