### PR TITLE
Modified highscore checking, Fixed port number display bug

### PR DESCRIPTION
**Pull request by JDHuber23**
The purpose of this change is to make sure that only scores of different games, or if the score is from the same game that it replaces the previous high score of the same game only if it is a higher score. This change is to address this improvement request on sourceforge: https://sourceforge.net/p/freecol/improvement-requests/226/

### CODE REVIEW

**Comment by JDHuber23** [comment]
These are two separate changes, the port number display bug is as described here: https://sourceforge.net/p/freecol/bugs/3215/

**Comment by mpope042** [comment]
The high score patch was incomplete, but a modified version has been committed (git.1740382 on sourceforge).

**Comment by mpope042** [comment]
Not sure what was intended in the first chunk of the port number fix, but it breaks i18n which is not acceptable.  A version of the spinner part in the second chunk has been committed in git.5dcb43c.  Thanks for that, you have been credited on the bug report followup.

**Comment by mpope042** [comment]
The unit-not-skipped fix is functionally correct, but is probably a "cant-please-everyone" situation.  Some people like to skip units with the intention of coming back to them, and thus *do* want them to show up in the end turn dialog.  My understanding is that this is consistent with the original intent that the "skip" command.  However, I concede that it is also common to want to leave a unit alone in the current turn.  On balance though I think this is handled sufficiently by just ending the turn anyway despite the unit appearing in the end turn dialog.  I recommend opening an Improvement Request if you have more to say on this subject.

That deals with all the items on this PR.  Apologies for the very slow response time.  If you have further FreeCol enhancements, please put them in seperate PRs, it makes it much easier to be sure we have looked at everything.  Closing.

**Pull request closed without merging**
